let ele
ele=document;
ele1=document.head;
ele2=document.body;
ele3=document.URL;
ele4=document.characterSet;
ele5=document.scripts;
ele6=document.images;
ele7=document.contentType;
ele8=document.forms;
ele9=document.forms[0];
ele10=document.forms[0].id;
ele11=document.forms[0].method;
ele12=document.forms[0].action;
ele13=document.links;
ele14=document.links[0].id;
ele15=document.links[0].className;
ele16=document.links;

console.log(ele)
console.log(ele1)
console.log(ele2)
console.log(ele3)
console.log(ele4)
console.log(ele5)
console.log(ele6)
console.log(ele7)
console.log(ele8)
console.log(ele9)
console.log(ele10)
console.log(ele11)
console.log(ele12)
console.log(ele13)
console.log(ele14)
console.log(ele15)
console.log(ele16)
